/* Allegro datafile object indexes, produced by grabber v4.1.11 (WIP), djgpp */
/* Datafile: e:\compi\revista3\sliders2.dat */
/* Date: Thu Dec 30 22:14:56 2004 */
/* Do not hand edit! */

#define FOTO_AMIGA_DISKMAG1              0        /* BMP  */
#define FOTO_AMIGA_DISKMAG2              1        /* BMP  */
#define FOTO_AMIGA_DISKMAG3              2        /* BMP  */
#define FOTO_BEOS_DUKE3D                 3        /* BMP  */
#define FOTO_BEOS_TECHNOID               4        /* BMP  */
#define FOTO_C64_DISKMAG1                5        /* BMP  */
#define FOTO_C64_DISKMAG2                6        /* BMP  */
#define FOTO_C64_DISKMAG3                7        /* BMP  */
#define FOTO_C64_DISKMAG4                8        /* BMP  */
#define FOTO_CDROM1                      9        /* BMP  */
#define FOTO_CDROM2                      10       /* BMP  */
#define FOTO_CDROM3                      11       /* BMP  */
#define FOTO_CDROM4                      12       /* BMP  */
#define FOTO_CONSOLAS_GB_DEMOS1          13       /* BMP  */
#define FOTO_CONSOLAS_GB_DEMOS2          14       /* BMP  */
#define FOTO_CONSOLAS_GB_DEMOS3          15       /* BMP  */
#define FOTO_CONSOLAS_GB_DEMOS4          16       /* BMP  */
#define FOTO_CONSOLAS_GB_DEMOS5          17       /* BMP  */
#define FOTO_CONSOLAS_GB_DEMOS6          18       /* BMP  */
#define FOTO_CONSOLAS_GB_DEMOS7          19       /* BMP  */
#define FOTO_CONSOLAS_GBA_BASIC          20       /* BMP  */
#define FOTO_CONSOLAS_GBA_DEMOS          21       /* BMP  */
#define FOTO_CONSOLAS_PSX_MANDO1         22       /* BMP  */
#define FOTO_CONSOLAS_PSX_MANDO2         23       /* BMP  */
#define FOTO_CPC_EUROCONECTOR            24       /* BMP  */
#define FOTO_CPC_OXYGEN1                 25       /* BMP  */
#define FOTO_CPC_OXYGEN2                 26       /* BMP  */
#define FOTO_CPC_TOOL                    27       /* BMP  */
#define FOTO_LENGUAJE_CMINUS             28       /* BMP  */
#define FOTO_LENGUAJE_CREATOR1           29       /* BMP  */
#define FOTO_LENGUAJE_CREATOR2           30       /* BMP  */
#define FOTO_LENGUAJE_DBASIC1            31       /* BMP  */
#define FOTO_LENGUAJE_DBASIC2            32       /* BMP  */
#define FOTO_LENGUAJE_POVRAY             33       /* BMP  */
#define FOTO_MSX1                        34       /* BMP  */
#define FOTO_MSX2                        35       /* BMP  */
#define FOTO_MSX3                        36       /* BMP  */
#define FOTO_MSX4                        37       /* BMP  */
#define FOTO_MSX5                        38       /* BMP  */
#define FOTO_MSX6                        39       /* BMP  */
#define FOTO_MSX_BMP1                    40       /* BMP  */
#define FOTO_MSX_BMP2                    41       /* BMP  */
#define FOTO_MSX_BMP3                    42       /* BMP  */
#define FOTO_MSX_HB55P1                  43       /* BMP  */
#define FOTO_MSX_HB55P2                  44       /* BMP  */
#define FOTO_NUEVOSOS_1                  45       /* BMP  */
#define FOTO_NUEVOSOS_2                  46       /* BMP  */
#define FOTO_NUEVOSOS_3                  47       /* BMP  */
#define FOTO_NUEVOSOS_4                  48       /* BMP  */
#define FOTO_PARTY_SOTA1                 49       /* BMP  */
#define FOTO_PARTY_SOTA2                 50       /* BMP  */
#define FOTO_PARTY_SOTA3                 51       /* BMP  */
#define FOTO_PARTY_SOTA4                 52       /* BMP  */
#define FOTO_PARTY_SOTA5                 53       /* BMP  */
#define FOTO_PC_DISKMAG1                 54       /* BMP  */
#define FOTO_PC_DISKMAG2                 55       /* BMP  */
#define FOTO_PC_DISKMAG3                 56       /* BMP  */
#define FOTO_PC_DISKMAG4                 57       /* BMP  */
#define FOTO_PC_DISKMAG5                 58       /* BMP  */
#define FOTO_PC_GRAFICA1                 59       /* BMP  */
#define FOTO_PC_GRAFICA2                 60       /* BMP  */
#define FOTO_PERSONAL_VACACIONES1        61       /* BMP  */
#define FOTO_PERSONAL_VACACIONES2        62       /* BMP  */
#define FOTO_PERSONAL_VACACIONES3        63       /* BMP  */
#define FOTO_RADIO_ALAN42_1              64       /* BMP  */
#define FOTO_RADIO_ALAN42_2              65       /* BMP  */
#define FOTO_RADIO_ALFAOMEGA1            66       /* BMP  */
#define FOTO_RADIO_ALFAOMEGA2            67       /* BMP  */
#define FOTO_RADIO_ALFAOMEGA3            68       /* BMP  */
#define FOTO_RADIO_ANTENA                69       /* BMP  */
#define FOTO_RADIO_FUENTE                70       /* BMP  */
#define FOTO_RADIO_PMR_1                 71       /* BMP  */
#define FOTO_RADIO_PMR_2                 72       /* BMP  */
#define FOTO_RADIO_PMR_3                 73       /* BMP  */
#define FOTO_RADIO_PRESIDENT_1           74       /* BMP  */
#define FOTO_RADIO_PRESIDENT_2           75       /* BMP  */
#define FOTO_RADIO_PRESIDENT_3           76       /* BMP  */
#define FOTO_RADIO_PTTSOUND_1            77       /* BMP  */
#define FOTO_RADIO_PTTSOUND_2            78       /* BMP  */
#define FOTO_RADIO_TRANSPARENCIAS        79       /* BMP  */
#define FOTO_REUNION_JORNADAS1           80       /* BMP  */
#define FOTO_REUNION_JORNADAS2           81       /* BMP  */
#define FOTO_REUNION_JORNADAS3           82       /* BMP  */
#define FOTO_REUNION_JORNADAS4           83       /* BMP  */
#define FOTO_REVISTA_EDITOR1             84       /* BMP  */
#define FOTO_REVISTA_EDITOR2             85       /* BMP  */
#define FOTO_REVISTA_MANEJO1             86       /* BMP  */
#define FOTO_REVISTA_OPINION1            87       /* BMP  */
#define FOTO_REVISTA_OPINION2            88       /* BMP  */
#define FOTO_REVISTA_PACK1               89       /* BMP  */
#define FOTO_REVISTA_PACK2               90       /* BMP  */
#define FOTO_REVISTA_PACK3               91       /* BMP  */
#define FOTO_REVISTA_PACK4               92       /* BMP  */
#define FOTO_REVISTA_PACK5               93       /* BMP  */
#define FOTO_REVISTA_PACK6               94       /* BMP  */
#define FOTO_VECTOR_1                    95       /* BMP  */
#define FOTO_VECTOR_2                    96       /* BMP  */
#define PALETA_AMIGA_DISKMAG1            97       /* PAL  */
#define PALETA_AMIGA_DISKMAG2            98       /* PAL  */
#define PALETA_AMIGA_DISKMAG3            99       /* PAL  */
#define PALETA_BEOS_DUKE3D               100      /* PAL  */
#define PALETA_BEOS_TECHNOID             101      /* PAL  */
#define PALETA_C64_DISKMAG1              102      /* PAL  */
#define PALETA_C64_DISKMAG2              103      /* PAL  */
#define PALETA_C64_DISKMAG3              104      /* PAL  */
#define PALETA_C64_DISKMAG4              105      /* PAL  */
#define PALETA_CDROM1                    106      /* PAL  */
#define PALETA_CDROM2                    107      /* PAL  */
#define PALETA_CDROM3                    108      /* PAL  */
#define PALETA_CDROM4                    109      /* PAL  */
#define PALETA_CONSOLAS_GB_DEMOS1        110      /* PAL  */
#define PALETA_CONSOLAS_GB_DEMOS2        111      /* PAL  */
#define PALETA_CONSOLAS_GB_DEMOS3        112      /* PAL  */
#define PALETA_CONSOLAS_GB_DEMOS4        113      /* PAL  */
#define PALETA_CONSOLAS_GB_DEMOS5        114      /* PAL  */
#define PALETA_CONSOLAS_GB_DEMOS6        115      /* PAL  */
#define PALETA_CONSOLAS_GB_DEMOS7        116      /* PAL  */
#define PALETA_CONSOLAS_GBA_BASIC        117      /* PAL  */
#define PALETA_CONSOLAS_GBA_DEMOS        118      /* PAL  */
#define PALETA_CONSOLAS_PSX_MANDO1       119      /* PAL  */
#define PALETA_CONSOLAS_PSX_MANDO2       120      /* PAL  */
#define PALETA_CPC_EUROCONECTOR          121      /* PAL  */
#define PALETA_CPC_OXYGEN1               122      /* PAL  */
#define PALETA_CPC_OXYGEN2               123      /* PAL  */
#define PALETA_CPC_TOOL                  124      /* PAL  */
#define PALETA_LENGUAJE_CMINUS           125      /* PAL  */
#define PALETA_LENGUAJE_CREATOR1         126      /* PAL  */
#define PALETA_LENGUAJE_CREATOR2         127      /* PAL  */
#define PALETA_LENGUAJE_DBASIC1          128      /* PAL  */
#define PALETA_LENGUAJE_DBASIC2          129      /* PAL  */
#define PALETA_LENGUAJE_POVRAY           130      /* PAL  */
#define PALETA_MSX1                      131      /* PAL  */
#define PALETA_MSX2                      132      /* PAL  */
#define PALETA_MSX3                      133      /* PAL  */
#define PALETA_MSX4                      134      /* PAL  */
#define PALETA_MSX5                      135      /* PAL  */
#define PALETA_MSX6                      136      /* PAL  */
#define PALETA_MSX_BMP1                  137      /* PAL  */
#define PALETA_MSX_BMP2                  138      /* PAL  */
#define PALETA_MSX_BMP3                  139      /* PAL  */
#define PALETA_MSX_HB55P1                140      /* PAL  */
#define PALETA_MSX_HB55P2                141      /* PAL  */
#define PALETA_NUEVOSOS_1                142      /* PAL  */
#define PALETA_NUEVOSOS_2                143      /* PAL  */
#define PALETA_NUEVOSOS_3                144      /* PAL  */
#define PALETA_NUEVOSOS_4                145      /* PAL  */
#define PALETA_PARTY_SOTA1               146      /* PAL  */
#define PALETA_PARTY_SOTA2               147      /* PAL  */
#define PALETA_PARTY_SOTA3               148      /* PAL  */
#define PALETA_PARTY_SOTA4               149      /* PAL  */
#define PALETA_PARTY_SOTA5               150      /* PAL  */
#define PALETA_PC_DISKMAG1               151      /* PAL  */
#define PALETA_PC_DISKMAG2               152      /* PAL  */
#define PALETA_PC_DISKMAG3               153      /* PAL  */
#define PALETA_PC_DISKMAG4               154      /* PAL  */
#define PALETA_PC_DISKMAG5               155      /* PAL  */
#define PALETA_PC_GRAFICA1               156      /* PAL  */
#define PALETA_PC_GRAFICA2               157      /* PAL  */
#define PALETA_PERSONAL_VACACIONES1      158      /* PAL  */
#define PALETA_PERSONAL_VACACIONES2      159      /* PAL  */
#define PALETA_PERSONAL_VACACIONES3      160      /* PAL  */
#define PALETA_RADIO_ALAN42_1            161      /* PAL  */
#define PALETA_RADIO_ALAN42_2            162      /* PAL  */
#define PALETA_RADIO_ALFAOMEGA1          163      /* PAL  */
#define PALETA_RADIO_ALFAOMEGA2          164      /* PAL  */
#define PALETA_RADIO_ALFAOMEGA3          165      /* PAL  */
#define PALETA_RADIO_ANTENA              166      /* PAL  */
#define PALETA_RADIO_FUENTE              167      /* PAL  */
#define PALETA_RADIO_PMR_1               168      /* PAL  */
#define PALETA_RADIO_PMR_2               169      /* PAL  */
#define PALETA_RADIO_PMR_3               170      /* PAL  */
#define PALETA_RADIO_PRESIDENT_1         171      /* PAL  */
#define PALETA_RADIO_PRESIDENT_2         172      /* PAL  */
#define PALETA_RADIO_PRESIDENT_3         173      /* PAL  */
#define PALETA_RADIO_PTTSOUND_1          174      /* PAL  */
#define PALETA_RADIO_PTTSOUND_2          175      /* PAL  */
#define PALETA_RADIO_TRANSPARENCIAS      176      /* PAL  */
#define PALETA_REUNION_JORNADAS1         177      /* PAL  */
#define PALETA_REUNION_JORNADAS2         178      /* PAL  */
#define PALETA_REUNION_JORNADAS3         179      /* PAL  */
#define PALETA_REUNION_JORNADAS4         180      /* PAL  */
#define PALETA_REVISTA_EDITOR1           181      /* PAL  */
#define PALETA_REVISTA_EDITOR2           182      /* PAL  */
#define PALETA_REVISTA_MANEJO1           183      /* PAL  */
#define PALETA_REVISTA_OPINION1          184      /* PAL  */
#define PALETA_REVISTA_OPINION2          185      /* PAL  */
#define PALETA_REVISTA_PACK1             186      /* PAL  */
#define PALETA_REVISTA_PACK2             187      /* PAL  */
#define PALETA_REVISTA_PACK3             188      /* PAL  */
#define PALETA_REVISTA_PACK4             189      /* PAL  */
#define PALETA_REVISTA_PACK5             190      /* PAL  */
#define PALETA_REVISTA_PACK6             191      /* PAL  */
#define PALETA_VECTOR_1                  192      /* PAL  */
#define PALETA_VECTOR_2                  193      /* PAL  */
#define TEXTO_AMIGA_DISKMAG              194      /* DATA */
#define TEXTO_BANDA                      195      /* DATA */
#define TEXTO_BEOS_DUKE3D                196      /* DATA */
#define TEXTO_BEOS_MAX                   197      /* DATA */
#define TEXTO_BEOS_TECHNOID              198      /* DATA */
#define TEXTO_BEOS_UPX                   199      /* DATA */
#define TEXTO_BEOS_XBEOS                 200      /* DATA */
#define TEXTO_BEOS_ZETA                  201      /* DATA */
#define TEXTO_C64_DISKMAG                202      /* DATA */
#define TEXTO_CDROM                      203      /* DATA */
#define TEXTO_CONSOLAS_GB_DEMOS          204      /* DATA */
#define TEXTO_CONSOLAS_GBA_BASIC         205      /* DATA */
#define TEXTO_CONSOLAS_GBA_DEMOS         206      /* DATA */
#define TEXTO_CONSOLAS_PSX_MANDO         207      /* DATA */
#define TEXTO_CPC_EUROCONECTOR           208      /* DATA */
#define TEXTO_CPC_OXYGEN                 209      /* DATA */
#define TEXTO_CPC_TECLADO                210      /* DATA */
#define TEXTO_CPC_TOOL                   211      /* DATA */
#define TEXTO_DOS_DRDOS                  212      /* DATA */
#define TEXTO_LENGUAJE_C                 213      /* DATA */
#define TEXTO_LENGUAJE_CMINUS            214      /* DATA */
#define TEXTO_LENGUAJE_CREATOR           215      /* DATA */
#define TEXTO_LENGUAJE_DBASIC            216      /* DATA */
#define TEXTO_LENGUAJE_MOONROCK          217      /* DATA */
#define TEXTO_LENGUAJE_POVRAY            218      /* DATA */
#define TEXTO_MSX                        219      /* DATA */
#define TEXTO_MSX_BMP                    220      /* DATA */
#define TEXTO_MSX_HB55P                  221      /* DATA */
#define TEXTO_NUEVOSOS                   222      /* DATA */
#define TEXTO_PARTY_SOTA                 223      /* DATA */
#define TEXTO_PC_CODEPIXEL               224      /* DATA */
#define TEXTO_PC_DISKMAG                 225      /* DATA */
#define TEXTO_PC_GRAFICA                 226      /* DATA */
#define TEXTO_PERSONAL_VACACIONES        227      /* DATA */
#define TEXTO_RADIO_ALAN42               228      /* DATA */
#define TEXTO_RADIO_ALFAOMEGA            229      /* DATA */
#define TEXTO_RADIO_ANTENA               230      /* DATA */
#define TEXTO_RADIO_ENTREVISTA           231      /* DATA */
#define TEXTO_RADIO_FUENTE               232      /* DATA */
#define TEXTO_RADIO_JJNET                233      /* DATA */
#define TEXTO_RADIO_LIBRO                234      /* DATA */
#define TEXTO_RADIO_OPCIONES             235      /* DATA */
#define TEXTO_RADIO_PLC                  236      /* DATA */
#define TEXTO_RADIO_PMR                  237      /* DATA */
#define TEXTO_RADIO_PMRVSCB              238      /* DATA */
#define TEXTO_RADIO_PRESIDENT            239      /* DATA */
#define TEXTO_RADIO_PTTSOUND             240      /* DATA */
#define TEXTO_RADIO_TRANSPARENCIAS       241      /* DATA */
#define TEXTO_REUNION_CONGRESO           242      /* DATA */
#define TEXTO_REUNION_JORNADAS           243      /* DATA */
#define TEXTO_REUNION_PARTIDOS           244      /* DATA */
#define TEXTO_REVISTA_EDITOR             245      /* DATA */
#define TEXTO_REVISTA_FORO               246      /* DATA */
#define TEXTO_REVISTA_MANEJO             247      /* DATA */
#define TEXTO_REVISTA_MINIDISKMAG        248      /* DATA */
#define TEXTO_REVISTA_OPINION            249      /* DATA */
#define TEXTO_REVISTA_PACK               250      /* DATA */
#define TEXTO_USBDOS                     251      /* DATA */
#define TEXTO_VECTOR                     252      /* DATA */

